[package]
name = "opensource_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "slicers"
path = "src/main.rs"

[features]
default = ["ra-hir"]
ra-hir = ["opensource_core/ra-hir"]

[dependencies]
opensource_core = { path = "../opensource_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
