[package]
name = "opensource_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
ra-hir = [
    "dep:ra_ap_hir",
    "dep:ra_ap_ide",
    "dep:ra_ap_load_cargo",
    "dep:ra_ap_project_model",
    "dep:ra_ap_syntax",
    "dep:ra_ap_vfs",
]

[dependencies]
prettyplease = "0.2"
proc-macro2.workspace = true
quote.workspace = true
ra_ap_hir = { version = "0.0.330", optional = true }
ra_ap_ide = { version = "0.0.330", optional = true }
ra_ap_load_cargo = { package = "ra_ap_load-cargo", version = "0.0.330", optional = true }
ra_ap_project_model = { version = "0.0.330", optional = true }
ra_ap_syntax = { version = "0.0.330", optional = true }
ra_ap_vfs = { version = "0.0.330", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn.workspace = true
toml = "0.8"
